#!/usr/bin/env python
# coding: utf-8
# comodit | A command line client for ComodIT

import sys
import json

from comodit_combox import setup, deploy, teardown, cleanup, control

def main(argv):

    config = get_config()
    if config is None:
        print "Failed to parse your comodit.conf file"
        sys.exit(-1)

    if not len(argv):
        print "Missing command"
        sys.exit(-1)

    command = argv[0]
    if command == 'setup':
        setup.setup(config)
    elif command == 'deploy':
        deploy.deploy(config)
    elif command == 'teardown':
        teardown.teardown(config)
    elif command == 'cleanup':
        cleanup.cleanup(config)
    elif command == 'start':
        control.start(config)
    elif command == 'stop':
        control.stop(config)
    else:
        print "Unknown command %s" % command
        sys.exit(-1)

def get_config():
    path = "./comodit.conf"
    with open(path,"r") as fd:
        content = fd.read()
        config = json.loads(content)
        return config

if __name__ == "__main__":
    main(sys.argv[1:])
